AllCops:
  Exclude:
    - 'spec/**/*'
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 150
  
Style/FileName:
  Enabled: false
